Feature/80 initialize user build desing documentation
amosproj/amos2023ws02-pitest-ide-plugin pull request #105
Opened 2023-12-04 18:23 UTC by QW3RAT

Added the 3 initialized documentations to the deliverables folder

2023-12-05 07:11 UTC, lheimbs requested changes
I don't think the layout should be centered, it looks a bit weird to me

2023-12-05 07:11 UTC, lheimbs commented on Deliverables/sprint-06/build-documentation.pdf.pdf
one too many `.pdf`

2023-12-06 11:10 UTC, QW3RAT commented
Fixed request by niko and added bold headlines

2023-12-06 11:20 UTC, nikomall34 commented
It looks better now so for me its fine. But what you can do is you can just copy the md code from the wiki page and open it in vscode. Vscode support a good md to pdf converter.
Check out the attached file 
[Untitled-1.pdf](https://github.com/amosproj/amos2023ws02-pitest-ide-plugin/files/13581673/Untitled-1.pdf)

2023-12-06 11:25 UTC, merged