add (validated) configuration for gradle plugin-publishing plugin
amosproj/amos2023ws02-pitest-ide-plugin pull request #147
Opened 2023-12-19 17:15 UTC by lfogarty98

- To publish our plugin to https://plugins.gradle.org/ another plugin needs to be configured: the Gradle plugin-publishing plugin :D 
- The configuration has been done by following the steps listed on https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html. These steps have also been validated by running the suggested command `./gradlew publishPlugins --validate-only`
- Since Gradle does not accept SNAPSHOT versions of projects I removed this from the `version` property

2023-12-19 18:52 UTC, lheimbs requested changes
this is the wrong build.gradle.kts if you want to publish the gradle partner plugin. the right one is in the partner plugin's folder and is already configured (except for the publish plugin iirc)

2023-12-19 18:53 UTC, QW3RAT commented
Maybe change the website part to the [README](https://github.com/amosproj/amos2023ws02-pitest-ide-plugin/blob/main/README.md)

2023-12-19 21:50 UTC, lfogarty98 commented
@lheimbs thanks for the pointer. But don't we want to publish our primary plugin too, i.e. the configuration added to pitmutationmate/build.gradle.kts should still be necessary? Maybe I'm misunderstanding what needs to exactly be published

2023-12-20 06:41 UTC, lheimbs commented
> don't we want to publish our primary plugin too, i.e. the configuration added to pitmutationmate/build.gradle.kts should still be necessary? Maybe I'm misunderstanding what needs to exactly be published

Well we don't want to publish the main plugin to the gradle plugin store which is what the `gradlePlugin` part is for.
Since we want to publish the primary plugin to the intellij store and not the gradle plugin store there i no need to add the information to the main plugin

2023-12-21 10:18 UTC, closed without merging