Feature/165 make plugin work with real data
amosproj/amos2023ws02-pitest-ide-plugin pull request #187
Opened 2024-01-22 15:23 UTC by QW3RAT

I hope i didnt missed some place where dummy data is being used

2024-01-22 17:05 UTC, lheimbs reviewed
I have not found any other occurences of dummy data that need to be removed but the `Package Breakdown` tab does not show any historical data. It always only shows me one entry.
Also it doesn't look the runs are getting archived.

2024-01-22 17:10 UTC, lheimbs approved these changes

2024-01-22 20:51 UTC, nikomall34 commented
Looks good! But in the ticket it says "Also get the archiving of the latest runs working again". I think this means you should also archive latest runs.
If you have time it would be also nice if you can fix the following behaviour. So when you open the IDE and you already have pitest reports they will get displayed. But when you go in you build file and remove one of the plugins and add them back then the results are not displayed again. It would be nice that if the pluginchecker is done the loading of pitest results is triggered.

2024-01-22 21:38 UTC, nikomall34 requested changes
When I run the pitest with more than 5 classes the summary does not contain real data. Please have a look at this.

2024-01-23 12:07 UTC, QW3RAT commented
Adressed requested changes

2024-01-23 12:45 UTC, lheimbs commented on pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/RunArchiver.kt
> +    private val reportDirectory: File = File(Paths.get(rootPiTestDirectoryPathName.toString(), "test").toString())
use the `ReportPathGeneratorService` here to get the path to the reports and also put the archive paths into the service

2024-01-23 12:45 UTC, lheimbs commented on pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/execution/BasePitestExecutor.kt
> +                    RunArchiver(classFQN, project).archiveRun()
Might be a good idea to run this asynchronous because for large files it could take a sec to move them

2024-01-23 12:45 UTC, lheimbs commented on pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/ui/ToolWindowFactory.kt
> +            }
the null check is unnecessary

2024-01-23 22:28 UTC, nikomall34 approved these changes

2024-01-23 22:29 UTC, merged