Feature/156 add the scope to the run configuration
amosproj/amos2023ws02-pitest-ide-plugin pull request #200
Opened 2024-01-22 17:53 UTC by brianneoberson

This feature was implemented slightly differently to what is written in the ticket. We decided to create a temporary run config whenever pitest is run from an action (gutter or context menu). This way the "pseudo-automatic" scope selection will always make sense. 

It didn't make sense to us that a "no overwrite" checkbox exists, because that would mean if the user creates a run config manually and checks this box, then the user would probably be confused as to why clicking the gutter run button next to the class doesn't run for that class (but for their manually defined scope). 

The user can set a scope manually through the Run Configuration editor and this scope will never be overwritten.

2024-01-22 19:08 UTC, lheimbs approved these changes
Works as described

2024-01-22 21:42 UTC, nikomall34 approved these changes

2024-01-22 22:27 UTC, nikomall34 commented
I guess it can be a bit annoying to add all the classes by hand. But tbh I don't really remember anymore why we wanted to implement this :D

2024-01-23 08:54 UTC, lheimbs requested changes
Sorry I have noticed an issue with this after all:

Right now we have the settings for the pitest task and the gradle executable in the run config settings. When the temporary run config is created in the action there is no way a user could set these...
I think that's one of the reasons the POs wanted the persistent run configs.

A way this could be mitigated is by checking all the existing run configs if there is one for the selected FQNs. If there is one use that otherwise create a new one... similar to how it was before.

Doing that no overwriting is needed (so the button can be left out) and the settings can still be changed.

--

Or we add a field "defaultRunConfig" to the run configs that is not changable by the user. Any manually created run configs get this set to false. The action only uses the one with `defaultRunConfig == true` and can create a persistent one if none exists.

--

Or the two settings are ditched all together ¯\_(ツ)_/¯

2024-01-23 15:16 UTC, lfogarty98 commented
@lheimbs 

> Right now we have the settings for the pitest task and the gradle executable in the run config settings. When the temporary run config is created in the action there is no way a user could set these... I think that's one of the reasons the POs wanted the persistent run configs.

Ok I see. It's not actually clear to me what these two settings are needed for in the first place. Is there documentation on this? Maybe @Felix-012 @emuguy1 can either of you give input here? As the ticket is rather vague

2024-01-23 15:39 UTC, lheimbs commented
well the task that is running pitest does not neccessarily have to be called `pitest` as the user can wrap another task around pitest to perform some sort of setup or so.
Of course that is very unlikely, same as a user not using the Gradle wrapper at it's default location.
But at some time there was a ticket to add more/other pitest settings to the run config settings so if that is still planned it also wouldn't work with how you have it now...

2024-01-23 16:58 UTC, emuguy1 commented
Well First of all, if something is unclear about the ticket, just ask. As always we answer as fast as possible. The reason We didnt want temporary run configs for something like actions and context menu, is so a user could have examples of how he has to define the scope if he wants to write a different one/ Keep often used scopes in configurations, so he doesnt need to select it every time. 
The idea was, that if the selected run config has a different scope than what is selected by a action, a new run config is created/ a existing not to be saved config is changed to have the new scope. Regarding the things lennard mentioned:
I think these settings we could move to something like a mutation mate property file as the IPs already mentioned for the problem with the android build type. Gonna talk to Felix about that, or we could talk about it tomorrow.

I think we could talk about just printing the scope to a specific spot so a user could copy it. But I also think the original propsed solution would probably be the best. What do you guys think?
@lheimbs @brianneoberson @lfogarty98 @nikomall34 

I hope this is understandable. If not please write further questions.

2024-01-23 19:25 UTC, lheimbs approved these changes
All right then i'll approve this based on it's doing what is says.
I don't mind not having the scope populated when running from an action because it's described in the run config how to enter the scopes.

Just one more note below

2024-01-23 23:00 UTC, merged