Feature/156 add scope to run config
amosproj/amos2023ws02-pitest-ide-plugin pull request #219
Opened 2024-01-29 10:40 UTC by brianneoberson

- created a "Default" run config which will be used for the actionable pitest runs 
- fixed the issue with the editing of run config settings. The editor now notices changes and they can be applied.

2024-01-29 19:45 UTC, lheimbs requested changes
I have a slight concern that users will add their custom class paths in the `Default` config then then wonder why they are gone after using some action...

2024-01-29 19:45 UTC, lheimbs commented on pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/configuration/RunConfiguration.kt
> +
Works but this seems like a weird work around.
What did work for me is setting the propertyName of the StoredProperty delegate in the RunConfigurationOptions correctly like so:

```
private var taskNameOption: StoredProperty<String?> = string("").provideDelegate(this, "taskName")
```

2024-01-30 09:09 UTC, nikomall34 requested changes
I noticed that when I restart my IDEA, my run configuration persists, but the options I entered in the Gradle task and target classes are lost.

2024-01-30 10:52 UTC, lheimbs commented on pitmutationmate/src/main/kotlin/com/amos/pitmutationmate/pitmutationmate/configuration/RunConfiguration.kt
> +
I have added the respective names here: b07053b9d3f9f8e1a0a6b3f43a0ac36d3bbbba4f

2024-01-30 16:27 UTC, brianneoberson commented
> I have a slight concern that users will add their custom class paths in the `Default` config then then wonder why they are gone after using some action...

I am afraid we won't have time to find and implement a solution for this until tomorrow. But this could be a small ticket for next sprint. We fixed the other requested changes.

2024-01-30 16:33 UTC, nikomall34 approved these changes

2024-01-30 16:35 UTC, nikomall34 commented
Maybe a quick fix could be to make the default runconfig not editable? Or maybe write somewhere in the Default run config "Please don't change".

2024-01-30 17:25 UTC, lheimbs approved these changes
I've added a simple solution to disable the `targetClasses` field when it is the default run config. All other configs' fields are still editable.

2024-01-30 17:57 UTC, nikomall34 commented
Unfortunately, I can still edit the default run configuration. I can simply modify the targetClasses in the run configuration, and when I click on "run" the specified classes are executed.

2024-01-30 17:59 UTC, lheimbs commented
> Unfortunately, I can still edit the default run configuration. I can simply modify the targetClasses in the run configuration, and when I click on "run" the specified classes are executed.

Did you remove the old one? Because that one obviously doesn't have the attribute set to true

2024-01-30 18:17 UTC, nikomall34 approved these changes
Ok works as expected!

2024-01-30 18:51 UTC, merged